import { Category } from "./types";

export const CATEGORIES: Category[] = [
  {
    slug: "natural-diamond",
    title: "Natural Diamonds",
    subtitle: "Eternal Heritage",
    description: "Rare, hand-selected natural diamonds crafted into high-end statements of luxury. Earth-mined stones chosen for peerless fire, clarity, and exceptional cut grading.",
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=800&auto=format&fit=crop",
    products: [
      {
        id: "nd-1",
        title: "Aura Solitaire Ring",
        price: "Price Upon Request",
        image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=nd-1",
      },
      {
        id: "nd-2",
        title: "Luminescence Drop Earrings",
        price: "Price Upon Request",
        image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=nd-2",
      },
      {
        id: "nd-3",
        title: "Imperial Diamond Choker",
        price: "Price Upon Request",
        image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=nd-3",
      },
      {
        id: "nd-4",
        title: "Elysian Diamond Bracelet",
        price: "Price Upon Request",
        image: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=nd-4",
      },
    ],
  },
  {
    slug: "lab-grown-diamond",
    title: "Lab-Grown Diamonds",
    subtitle: "Conscious Innovation",
    description: "Ethical, premium lab-grown diamond creations displaying identical physical properties and matching scintillation. For the modern collector seeking conscious beauty.",
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=800&auto=format&fit=crop",
    products: [
      {
        id: "lgd-1",
        title: "Nova Halo Ring",
        price: "INR 1,20,000 - INR 2,80,000",
        image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=lgd-1",
      },
      {
        id: "lgd-2",
        title: "Celestial Studs",
        price: "INR 80,000 - INR 1,50,000",
        image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=lgd-2",
      },
      {
        id: "lgd-3",
        title: "Infinity Diamond Band",
        price: "INR 95,000 - INR 1,80,000",
        image: "https://images.unsplash.com/photo-1610398087193-41c1d81d1575?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=lgd-3",
      },
      {
        id: "lgd-4",
        title: "Solaris Tennis Necklace",
        price: "INR 4,50,000 - INR 8,000,000",
        image: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=lgd-4",
      },
    ],
  },
  {
    slug: "gold",
    title: "Gold Heritage",
    subtitle: "Pure Lustre",
    description: "Sculpted 18k and 22k solid gold masterpieces designed for the modern connoisseur. Featuring detailed hand-carved textures and classic editorial shapes.",
    image: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?q=80&w=800&auto=format&fit=crop",
    products: [
      {
        id: "g-1",
        title: "Sienna Gold Bangle Set",
        price: "Price Upon Request",
        image: "https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=g-1",
      },
      {
        id: "g-2",
        title: "Heritage Filigree Necklace",
        price: "Price Upon Request",
        image: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=g-2",
      },
      {
        id: "g-3",
        title: "Classic Gold Hoop Earrings",
        price: "INR 65,000 - INR 1,20,000",
        image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=g-3",
      },
      {
        id: "g-4",
        title: "Textured Solid Gold Band",
        price: "INR 45,000 - INR 90,000",
        image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=g-4",
      },
    ],
  },
  {
    slug: "polki",
    title: "Heritage Polki",
    subtitle: "Ancestral Majesty",
    description: "Traditional Indian craftsmanship detailing raw, uncut diamonds set in fine gold foil backings. Rich designs passed down through generations of royal ateliers.",
    image: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=800&auto=format&fit=crop",
    products: [
      {
        id: "p-1",
        title: "Durbar Polki Choker",
        price: "Price Upon Request",
        image: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=p-1",
      },
      {
        id: "p-2",
        title: "Chandbali Polki Earrings",
        price: "Price Upon Request",
        image: "https://images.unsplash.com/photo-1603006905003-be475563bc59?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=p-2",
      },
      {
        id: "p-3",
        title: "Mayur Polki Kada",
        price: "Price Upon Request",
        image: "https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=p-3",
      },
      {
        id: "p-4",
        title: "Royal Polki Ring",
        price: "Price Upon Request",
        image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=p-4",
      },
    ],
  },
  {
    slug: "kundan",
    title: "Royal Kundan",
    subtitle: "Imperial Enamel",
    description: "Exquisite pure gold foil setting matching dynamic gemstone encrustations and hand-drawn Meenakari enamelling on the reverse surfaces.",
    image: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=800&auto=format&fit=crop",
    products: [
      {
        id: "k-1",
        title: "Rajkumari Kundan Necklace",
        price: "Price Upon Request",
        image: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=k-1",
      },
      {
        id: "k-2",
        title: "Zardozi Kundan Jhumkas",
        price: "Price Upon Request",
        image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=k-2",
      },
      {
        id: "k-3",
        title: "Kundan Mathapatti",
        price: "Price Upon Request",
        image: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=k-3",
      },
      {
        id: "k-4",
        title: "Mughal Kundan Bangles",
        price: "Price Upon Request",
        image: "https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=k-4",
      },
    ],
  },
  {
    slug: "bridal",
    title: "Bridal Heritage",
    subtitle: "The Signature Trousseau",
    description: "Grand, high-end bridal sets crafted to capture the eternal spirit of your union. Intricately composed layers of gold, diamonds, and heritage accents.",
    image: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=800&auto=format&fit=crop",
    products: [
      {
        id: "b-1",
        title: "The Maharani Bridal Set",
        price: "Price Upon Request",
        image: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=b-1",
      },
      {
        id: "b-2",
        title: "Elysian Bridal Choker",
        price: "Price Upon Request",
        image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=b-2",
      },
      {
        id: "b-3",
        title: "Bridal Polki Jhumkas",
        price: "Price Upon Request",
        image: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=b-3",
      },
      {
        id: "b-4",
        title: "Bridal Diamond Haathphool",
        price: "Price Upon Request",
        image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=600&auto=format&fit=crop",
        href: "/contact?inquiry=b-4",
      },
    ],
  },
];
